### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by kimslawson** [ququplay/jquery-mobile-ios8-theme#1]
I can't wait to use this in my projects. Wondering what the status is?

**Comment by psychonelo** [comment]
Is this theme ready?

**Comment by mkuklis** [comment]
Yes you can purchase it here: http://store.ququplay.com

**Comment by psychonelo** [comment]
It is too late! We already moved from jQuery Mobile to Framework7.

**Comment by nurtayak** [comment]
If i purchase it, and you update this theme. Can i get newer version?
can this theme load be faster ?
